services:
  - type: web
    name: kidmate-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: mysql+pymysql://u632760522_kidmate:mIN?mQ]S5@109.106.246.51:3306/u632760522_kidmate
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true 