"""move_dropoff_location_to_journey

Revision ID: 6271232e2a24
Revises: 8d474fc2857f
Create Date: 2025-08-16 14:54:27.107502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6271232e2a24'
down_revision = '8d474fc2857f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add drop-off location fields to pickup_journey table
    with op.batch_alter_table('pickup_journey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropoff_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dropoff_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_longitude', sa.Float(), nullable=True))

    # Remove drop-off location fields from pickup_persons table
    with op.batch_alter_table('pickup_persons', schema=None) as batch_op:
        batch_op.drop_column('dropoff_longitude')
        batch_op.drop_column('dropoff_location')
        batch_op.drop_column('dropoff_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add drop-off location fields back to pickup_persons table
    with op.batch_alter_table('pickup_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropoff_latitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_location', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('dropoff_longitude', mysql.FLOAT(), nullable=True))

    # Remove drop-off location fields from pickup_journey table
    with op.batch_alter_table('pickup_journey', schema=None) as batch_op:
        batch_op.drop_column('dropoff_longitude')
        batch_op.drop_column('dropoff_latitude')
        batch_op.drop_column('dropoff_location')

    # ### end Alembic commands ###
