"""Initial pickup_journey table

Revision ID: 88a04991bcfe
Revises: 1dc86cd7aeb8
Create Date: 2025-06-08 13:05:41.154017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88a04991bcfe'
down_revision = '1dc86cd7aeb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pickup_journey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('child_id', sa.String(length=36), nullable=False),
    sa.Column('pickup_person_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_admin', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('phone')

    op.drop_table('users_admin')
    op.drop_table('attendance')
    with op.batch_alter_table('pickup_journeys', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('pickup_journeys')
    op.drop_table('schools')
    op.drop_table('grades')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('payment_id')

    op.drop_table('payments')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('occupation')
        batch_op.drop_column('email')
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', mysql.ENUM('Father', 'Mother', 'Auntie', 'Uncle', 'Brother', 'Sister', ''), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('occupation', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=200), nullable=True))

    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('payment_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('kid_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('term_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_status', mysql.ENUM('Paid', 'Partial', 'Pending'), server_default=sa.text("'Paid'"), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('payment_id', ['payment_id'], unique=True)

    op.create_table('grades',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kid_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('grade', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('date_recorded', sa.DATE(), nullable=True),
    sa.Column('remarks', mysql.VARCHAR(length=255), server_default=sa.text("'PASS'"), nullable=False),
    sa.Column('comments', mysql.VARCHAR(length=255), server_default=sa.text("'Good Behavior'"), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], name='grades_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('schools',
    sa.Column('school_id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('school_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('school_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('school_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pickup_journeys',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('pickup_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('parent_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('child_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('pickup_person_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pickup_journeys', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('attendance',
    sa.Column('attendance_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kid_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('Present', 'Absent', 'Late'), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['kid_id'], ['kids.id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('attendance_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users_admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('push_token', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users_admin', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('pickup_journey')
    # ### end Alembic commands ###
