"""Add is_active field to PickupPerson model

Revision ID: 91555632debe
Revises: 
Create Date: 2025-08-14 17:47:31.681570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91555632debe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index('unique_user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index('unique_user_email', ['user_email'], unique=True)

    # ### end Alembic commands ###
