"""Add dropoff location fields to PickupPerson model

Revision ID: add_dropoff_location
Revises: 91555632debe
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_dropoff_location'
down_revision = '91555632debe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dropoff_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dropoff_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dropoff_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_persons', schema=None) as batch_op:
        batch_op.drop_column('dropoff_longitude')
        batch_op.drop_column('dropoff_latitude')
        batch_op.drop_column('dropoff_location')
        batch_op.drop_column('phone')

    # ### end Alembic commands ### 