"""Add missing model classes for admin_users, terms, subjects, classes, grades

Revision ID: b735851e31e6
Revises: 91555632debe
Create Date: 2025-08-14 17:52:55.708047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b735851e31e6'
down_revision = '91555632debe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('grades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'kids', ['kid_id'], ['id'])

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index('unique_user_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index('unique_user_email', ['user_email'], unique=True)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_1', 'kids', ['kid_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
