"""add_user_email_foreign_key_to_parents

Revision ID: fad7cfc49f41
Revises: 15fdf959beff
Create Date: 2025-08-02 08:52:11.259114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fad7cfc49f41'
down_revision = '15fdf959beff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])
        batch_op.drop_column('relationship')
        batch_op.drop_column('address')
        batch_op.drop_column('user_id')
        batch_op.drop_column('occupation')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('occupation', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('relationship', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
